version: "3"

services:
  db:
    image: postgres:11.2
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - "dbdata:/var/lib/postgresql/data"
  pgadmin:
    image: dpage/pgadmin4:4.4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "80:80"
    volumes:
      - "pgadmindata:/var/lib/pgadmin"
      - "./servers.json:/pgadmin4/servers.json"

volumes:
  dbdata:
  pgadmindata:
